### ISSUE TITLE
Great tool!

### ISSUE THREAD

**Issue by sdhutchins** [enthought/vpsearch#31]
Hey, @jvkersch! I like this tool a lot. I had to use blast a great deal in the past, and I think this will be very useful once it's published and gains some traction. I'd encourage posting about on https://www.reddit.com/r/bioinformatics/. 

Also, I think it'd be helpful to add some badges to the readme and other metrics.

People often look for the below: 

- [ ] Code coverage - you already have a great testing infrastructure built so this should be easy.
- [x] Pypi badge - (https://badge.fury.io/for/py/vpsearch)

Neither of those things is required for my review, but I do think they'd help tremendously when people visit the GitHub page to see that.

**Comment by jvkersch** [comment]
@sdhutchins I've added the badges to the README. I agree that this would be a good to have, to reflect the status of the project in one look. I added the PyPI badge that you mentioned, and also one to show the status of the tests upon pushes to the main branch. I didn't add the coverage badge, as that would (AFAICT) involve another external service, something that I'd like to avoid. I'll close this issue as fixed, but please feel free to reopen if necessary.
