### ISSUE TITLE
Consider enabling GitHub actions?

### ISSUE THREAD

**Issue by jvkersch** [enthought/vpsearch#9]
It would probably be good to bring this repo in line with other Enthought open source projects, and move away from Travis to GitHub actions. I'm also interested in potentially building and publishing wheels using GitHub actions, though that may be a bit more tricky (see https://github.com/enthought/vpsearch/pull/8). 

Would it be possible to enable GitHub actions for this repo? I can put in a quick PR to update the CI.

**Comment by rahulporuri** [comment]
> Would it be possible to enable GitHub actions for this repo?

Should be possible. I'll put in a request internally.

**Comment by rahulporuri** [comment]
> I'm also interested in potentially building and publishing wheels using GitHub actions, though that may be a bit more tricky (see #8).

@mdickinson has this figured out for Traits - https://github.com/enthought/traits/blob/b343ea87a02c74f9b74c16efe6a02bd3d883eccb/.github/workflows/upload-to-pypi.yml. Not sure if you already knew about it.

**Comment by rahulporuri** [comment]
@jvkersch GitHub Actions CI has been enabled for this repository.
